--- 
abstract: Data lottery module by its own weight
author: 
  - Takeshi Miki <miki@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.70
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Data-Lotter
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Fast: 0
  perl: 5.8.1
version: 0.00001
